manifest:
#  defaults:
#  revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: george-norton
      url-base: https://github.com/george-norton
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: main
    - name: zmk-driver-pmw3360
      remote: george-norton
      revision: main
    - name: zmk-input-processor-report-rate-limit
      remote: badjeff
      revision: main
  self:
    path: config
